---
title: "Learning to program in R with mineR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Learn to program in Minecraft with mineR}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The mineR package provides a simple interface to the Minecraft world. Use R functions
to connect with a Minecraft server and control the world within.

The purpose of this package is to teach new programmers about R. See the effect of
your R programs directly in Minecraft!

### Installation

To install this package:

```r
# install.packages("devtools")
library(devtools)
devtools::install_github('ropenscilabs/miner')
```

To use the package you will need to:

* Install a Minecraft server
* Install a Minecraft client (the Minecraft game)
* Connect to the Minecraft server from R

```r
library(miner)
mc_connect('52.1.2.3') ## use your server IP address here, or 127.0.0.1 if installed locally
```

### About Minecraft

Minecraft is a virtual world, arranged as a 3-D grid of blocks of various materials
(air, wood, stone, etc) and populated by players, animals and monsters. The state of 
the world is maintained by a shared Minecraft server, and players explore and interact
with the shared world using a local Minecraft client.

For the server, we installed [Spigot](https://www.spigotmc.org/), an open-source
Minecraft server, on a virtual machine. (See the section 
"Details on setting up a Minecraft Server", below.) The R functions in this package
connect with the server and modify the game world.

For the client, you will need to purchase and install [Minecraft](https://minecraft.net) on 
your local PC or Mac machine. Note: this package will not work with Pocket Minecraft on mobile
devices/tablets, or with the Windows 10 version of Minecraft found in the Windows Store.

## Your first mineR adventure

Once you have a Minecraft server set up, here are some commands you can try. Use your Minecraft
client to observe the changes these commands make to the world.

First, connect to the world. For this you will need to know the IP address of your server.

```
mc_connect("52.168.1.2") # use the IP of your server here
```

To check you have successfully connected to the world, you can try chatting. You should
see this message appear in the feed in the Minecraft client.

```r
chatPost("Message goes to all players.")
```

Each player in the world gets a "player ID"", and you'll need to know the player ID to manipulate
players. If you're the only player in the world, the player ID is
easy to find. But if there are multiple players, the easiest way to find your ID is 
to sign out of the server and then sign in again. Your player ID will then be the last
one on the list returned by `getPlayerIds`.

```r
myid <- tail(getPlayerIds(),1) 
```

Once you have a Player ID, you can move the player around. Note that in Minecraft, "x"
is the North/South axis, "z" is the East/West axis, and "y" is the vertical axis.

```r
myloc <- getPlayerPost(myid)
setPlayerPos(myloc[1]+1,myloc[2],myloc[3],player_id=myid)  # move player 1 tile North
setPlayerPos(myloc[1],myloc[2]+50,myloc[3],player_id=myid) # raise player 50 tiles in the air
```

You can also modify the game world. For example, this adds a diamond block near the player.
(You can find a [list of block ids here](http://minecraft-ids.grahamedgecombe.com/).)

```r
myloc <- getPlayerPos(myid)
setBlock(myloc[1]+1, myloc[2], myloc[3], 57, 1)
```

## Overview of mineR commands

Functions you can use:

* `mc_connect`: Connect to a MineCraft server
* `getPlayerIds`: Get a list of players in the world
* 


## Suggestions for writing your own programs with mineR

Using the commands above, you can write programs in R to create structures in the game world,
manipulate players, or even have the game world react to actions players take. Here are
some things you can try (in some cases, with links to examples showing how).

* Take an image, and create a wall in Minecraft that looks like the image.
* Build a random maze to explore in Minecraft.
* Make it possible to run over water, by having ice appear wherever water touches
  the player's feet.
  
  
## Details on Setting up a Minecraft server

We have tested this package using Spigot installed on an Ubuntu 16.04 virtual machine.

You may need to open ports on the Minecraft server to allow R and game clients to connect with 
it.

You probably want to configure the server to run in Creative mode. (How?)

## Acknowledgments and References

Many of the ideas and techniques in this package were adapted from 
"Learn to program with Minecraft" by Craid Richardson. (No Starch Press, 2016)